openapi: 3.0.0
info:
  title: Todo AI Chatbot API
  version: 1.0.0
  description: Natural language interface for todo management

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.example.com
    description: Production server

paths:
  /api/chat:
    post:
      summary: Send message to AI chatbot
      description: |
        Send a natural language message to the AI chatbot for todo management.
        The chatbot can create, view, update, complete, and delete tasks based on user intent.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  minLength: 1
                  maxLength: 10000
                  description: User's natural language message
                  example: "Add a task to buy groceries tomorrow"
                conversation_id:
                  type: string
                  format: uuid
                  description: Existing conversation ID (omit for new conversation)
                  example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - conversation_id
                  - response
                  - timestamp
                properties:
                  success:
                    type: boolean
                    example: true
                  conversation_id:
                    type: string
                    format: uuid
                    description: Conversation ID for this thread
                    example: "550e8400-e29b-41d4-a716-446655440000"
                  response:
                    type: string
                    description: AI-generated natural language response
                    example: "I've created a task for you: 'buy groceries' with a due date of February 12, 2026."
                  timestamp:
                    type: string
                    format: date-time
                    description: When the response was generated
                    example: "2026-02-11T22:00:00Z"
                  tools_used:
                    type: array
                    items:
                      type: string
                    description: MCP tools invoked during processing
                    example: ["add_task"]
                  context:
                    type: object
                    description: Metadata about operations performed
                    properties:
                      tasks_affected:
                        type: integer
                        description: Number of tasks affected by this operation
                        example: 1
                      operation:
                        type: string
                        enum: [create, read, update, delete, complete]
                        description: Type of operation performed
                        example: "create"
        '400':
          description: Bad request (validation error)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                error: "validation_error"
                message: "Message is required and must be 1-10000 characters"
        '401':
          description: Unauthorized (invalid/expired token)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                error: "unauthorized"
                message: "Invalid or expired token"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                success: false
                error: "internal_error"
                message: "An error occurred processing your request"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from Better Auth authentication

  schemas:
    Error:
      type: object
      required:
        - success
        - error
        - message
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          description: Error code
          example: "validation_error"
        message:
          type: string
          description: Human-readable error message
          example: "Message is required"
